### ISSUE TITLE
Issues with spaces in filenames with NetStorageKit-3.6.6.jar library

### ISSUE THREAD

**Issue by poonamraj1** [akamai/NetStorageKit-Java#22]
Seeing the following error when the filename contains a space:

Exception in thread "main" com.akamai.netstorage.NetStorageException: com.akamai.netstorage.NetStorageException: Communication Error
at com.akamai.netstorage.NetStorage.execute(NetStorage.java:71)
at com.akamai.netstorage.NetStorage.upload(NetStorage.java:258)
at com.akamai.netstorage.NetStorage.upload(NetStorage.java:287)
at com.akamai.netstorage.NetStorage.upload(NetStorage.java:265)
at ns.uploadToAkamai(ns.java:33)
at ns.doIt(ns.java:38)
at ns.main(ns.java:19)
Caused by: com.akamai.netstorage.NetStorageException: Communication Error
at com.akamai.netstorage.NetStorageCMSv35Signer.execute(NetStorageCMSv35Signer.java:359)
at com.akamai.netstorage.NetStorageCMSv35Signer.execute(NetStorageCMSv35Signer.java:364)
at com.akamai.netstorage.NetStorage.execute(NetStorage.java:68)
... 6 more
Caused by: com.akamai.netstorage.NetStorageException: Unexpected Response from Server: 400 Bad Request
{null=[HTTP/1.1 400 Bad Request], Cache-Control=[max-age=0, no-cache, no-store], Server=[Apache], Connection=[close], Pragma=[no-cache], Expires=[Thu, 16 Aug 2018 21:51:34 GMT], Date=[Thu, 16 Aug 2018 21:51:34 GMT], Content-Type=[text/html; charset=iso-8859-1]}
at com.akamai.netstorage.NetStorageCMSv35Signer.validate(NetStorageCMSv35Signer.java:281)
at com.akamai.netstorage.NetStorageCMSv35Signer.execute(NetStorageCMSv35Signer.java:348)
... 8 more
%

**Comment by WallTearer** [comment]
Yes, I can confirm this bug. I'm getting exactly the same exception when trying to upload a file that has spaces in the name.
Using NetStorageKit-3.6.6.jar as well.

**Comment by vladonemo** [comment]
I'm running to the same issue

**Comment by chasetec** [comment]
Did you try replacing the spaces?

**Comment by chasetec** [comment]
It'd be nice if NetStorage.getNetstorageUri handled this automatically.
